### PR TITLE
Multi controller

### PR DESCRIPTION
**Pull request by mattmoor**
Fixes https://github.com/grantr/helloworld-crd/issues/11

### CODE REVIEW

**Comment by mattmoor** [comment]
So when I create `Bar` resources with this, I see:
```shell
E0109 16:21:10.645971       1 streamwatcher.go:109] Unable to decode an event from the watch stream: unable to decode watch event: no kind "Bar" is registered for version "samplecontroller.k8s.io/v1alpha1"
W0109 16:21:10.649970       1 reflector.go:341] pkg/client/informers/externalversions/factory.go:74: watch of *v1alpha1.Bar ended with: too old resource version: 319103 (319161)
I0109 16:21:11.657989       1 controller.go:199] Successfully synced 'default/example-bar'
I0109 16:21:11.659273       1 event.go:218] Event(v1.ObjectReference{Kind:"Bar", Namespace:"default", Name:"example-bar", UID:"1aac4d83-f559-11e7-89e0-42010a80010b", APIVersion:"samplecontroller.k8s.io/v1alpha1", ResourceVersion:"319162", FieldPath:""}): type: 'Normal' reason: 'Synced' Bar synced successfully
```

I think it's because the `Foo` controller is somehow receiving a `Bar`, probably because [all of their clients are shared](https://github.com/mattmoor/sample-controller/blob/775be3f7ea122b6b8bcb8e6b15e0b69744859ac5/main.go#L66).

**Comment by mattmoor** [comment]
I rebased this on your RBAC commit.

**Comment by grantr** [comment]
> probably because all of their clients are shared.

Instead of having a single meta-controller wrap two controllers, could we have two controllers that are both managed by the top-level `main.go`? Then each informer would just have to deal with a single type.

**Comment by mattmoor** [comment]
> Then each informer would just have to deal with a single type.

Even if I push the client and informer creation all the way in, I see the above error, so I'm not sure it's related to my initial hypothesis. :(

**Comment by mattmoor** [comment]
This should be RFAL

**Comment by grantr** [comment]
@mattmoor Haven't tested it yet, btu I wonder if that error is caused by not adding `Bar` to this list: https://github.com/grantr/helloworld-crd/blob/fe6b4028e3d1e415bfcdb0a17cf624987b2d2b37/pkg/apis/samplecontroller/v1alpha1/register.go#L47-L50

**Comment by mattmoor** [comment]
Good find.  Do you want to try it and send me a PR?  If not, I can try things out tomorrow.

**Comment by grantr** [comment]
That was it. PR at #14.

**Pull request merged**
